export const CATEGORIES = [
  "Academic Support",
  "Language Practice",
  "Tech/Digital Help",
  "Errands/Delivery",
  "Campus Navigation",
  "Peer Companionship",
  "Lifestyle & Arts",
  "Other"
];

export const LANGUAGES_LIST = [
  "English",
  "Mandarin Chinese",
  "Spanish",
  "Hindi",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Bahasa Indonesia",
  "Urdu",
  "German",
  "Japanese",
  "Swahili",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Yue Chinese (Cantonese)",
  "Vietnamese",
  "Tagalog",
  "Korean",
  "French",
  "Italian",
  "Thai",
  "Gujarati",
  "Persian",
  "Polish",
  "Malayalam",
  "Odia",
  "Maithili",
  "Burmese",
  "Hakka Chinese",
  "Bhojpuri",
  "Sign Language",
  "Other"
];

export const SKILLS_LIST = [
  "Programming (Python/Java/C++)",
  "Web Development (React/Node)",
  "Mobile App Development",
  "Data Analysis & Excel",
  "Mathematics & Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Graphic Design (Photoshop/Illustrator)",
  "UI/UX Design",
  "Video Editing (Premiere/Final Cut)",
  "Photography",
  "Copywriting & Editing",
  "Translation & Interpretation",
  "Public Speaking & Presentation",
  "Event Planning & Management",
  "Marketing & Social Media",
  "Accounting & Finance",
  "Business Strategy",
  "Tutoring & Academic Mentoring",
  "Language Teaching (English/Mandarin/Malay etc.)",
  "Music & Instrument Tutoring",
  "Cooking & Baking",
  "Fitness Coaching",
  "Career Advice & Resume Review",
  "Hardware & PC Building",
  "3D Modeling & Animation",
  "Game Development",
  "Cybersecurity",
  "Blockchain & Web3",
  "Digital Illustration",
  "Animation",
  "SEO & Digital Marketing",
  "Project Management",
  "Video Production",
  "Audio Engineering"
];
